### ISSUE TITLE
如何解决直播前设备访问twitch的问题

### ISSUE THREAD

**Issue by raykimurayyz** [7YHong/nginx-rtmp#1]
1. 将ps5的dns地址设置为docker-dnsmasq
2. docker-dnsmasq中的twitch.tv解析IP地址设置为docker宿主机的IP
3. docker中安装了本nginx-rtmp

理论上来说ps5访问twitch.tv域名的时候会被解析到nginx-rtmp所在的ip，然后推流到国内的平台

但是推流前会先访问twtich.tv查询相关信息（443端口），此处需要通过nginx的正向代理+科学上网吗？

**Comment by 7YHong** [comment]
> 1. 将ps5的dns地址设置为docker-dnsmasq
> 2. docker-dnsmasq中的twitch.tv解析IP地址设置为docker宿主机的IP
> 3. docker中安装了本nginx-rtmp
> 
> 理论上来说ps5访问twitch.tv域名的时候会被解析到nginx-rtmp所在的ip，然后推流到国内的平台
> 
> 但是推流前会先访问twtich.tv查询相关信息（443端口），此处需要通过nginx的正向代理+科学上网吗？

`api.twitch.tv`, `ingest.twitch.tv` ，这 2 个域名必须要科学上网
只需要劫持`*.contribute.live-video.net:1935`域名即可

**Comment by raykimurayyz** [comment]
可以了，感谢大佬
我以为代理会自动实现所有DNS解析，然而PS主机好似并不是这样
我设置了DNS以后，系统会根据目标的DNS服务器拦截指定域名，从而实现了定向截流
