### ISSUE TITLE
有没有办法实现ps主机的弹幕重定向

### ISSUE THREAD

**Issue by raykimurayyz** [7YHong/nginx-rtmp#2]
twitch用的弹幕是irc的聊天室协议，能不能劫持irc.twitch.tv的弹幕信息，重定向到b站呢？

**Comment by 7YHong** [comment]
> twitch用的弹幕是irc的聊天室协议，能不能劫持irc.twitch.tv的弹幕信息，重定向到b站呢？

也许可以单独写个程序，把弹幕从twitch上拉下来
